
package control;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ControleInterface", targetNamespace = "http://control/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ControleInterface {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "postCelular", targetNamespace = "http://control/", className = "control.PostCelular")
    @ResponseWrapper(localName = "postCelularResponse", targetNamespace = "http://control/", className = "control.PostCelularResponse")
    @Action(input = "http://control/ControleInterface/postCelularRequest", output = "http://control/ControleInterface/postCelularResponse")
    public void postCelular(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "postCapinha", targetNamespace = "http://control/", className = "control.PostCapinha")
    @ResponseWrapper(localName = "postCapinhaResponse", targetNamespace = "http://control/", className = "control.PostCapinhaResponse")
    @Action(input = "http://control/ControleInterface/postCapinhaRequest", output = "http://control/ControleInterface/postCapinhaResponse")
    public void postCapinha(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delCelular", targetNamespace = "http://control/", className = "control.DelCelular")
    @ResponseWrapper(localName = "delCelularResponse", targetNamespace = "http://control/", className = "control.DelCelularResponse")
    @Action(input = "http://control/ControleInterface/delCelularRequest", output = "http://control/ControleInterface/delCelularResponse")
    public String delCelular(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCapinhaId", targetNamespace = "http://control/", className = "control.GetCapinhaId")
    @ResponseWrapper(localName = "getCapinhaIdResponse", targetNamespace = "http://control/", className = "control.GetCapinhaIdResponse")
    @Action(input = "http://control/ControleInterface/getCapinhaIdRequest", output = "http://control/ControleInterface/getCapinhaIdResponse")
    public String getCapinhaId(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCelularId", targetNamespace = "http://control/", className = "control.GetCelularId")
    @ResponseWrapper(localName = "getCelularIdResponse", targetNamespace = "http://control/", className = "control.GetCelularIdResponse")
    @Action(input = "http://control/ControleInterface/getCelularIdRequest", output = "http://control/ControleInterface/getCelularIdResponse")
    public String getCelularId(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "putCelular", targetNamespace = "http://control/", className = "control.PutCelular")
    @ResponseWrapper(localName = "putCelularResponse", targetNamespace = "http://control/", className = "control.PutCelularResponse")
    @Action(input = "http://control/ControleInterface/putCelularRequest", output = "http://control/ControleInterface/putCelularResponse")
    public void putCelular(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "putCapinha", targetNamespace = "http://control/", className = "control.PutCapinha")
    @ResponseWrapper(localName = "putCapinhaResponse", targetNamespace = "http://control/", className = "control.PutCapinhaResponse")
    @Action(input = "http://control/ControleInterface/putCapinhaRequest", output = "http://control/ControleInterface/putCapinhaResponse")
    public void putCapinha(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delCapinha", targetNamespace = "http://control/", className = "control.DelCapinha")
    @ResponseWrapper(localName = "delCapinhaResponse", targetNamespace = "http://control/", className = "control.DelCapinhaResponse")
    @Action(input = "http://control/ControleInterface/delCapinhaRequest", output = "http://control/ControleInterface/delCapinhaResponse")
    public String delCapinha(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCelular", targetNamespace = "http://control/", className = "control.GetCelular")
    @ResponseWrapper(localName = "getCelularResponse", targetNamespace = "http://control/", className = "control.GetCelularResponse")
    @Action(input = "http://control/ControleInterface/getCelularRequest", output = "http://control/ControleInterface/getCelularResponse")
    public String getCelular();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCapinha", targetNamespace = "http://control/", className = "control.GetCapinha")
    @ResponseWrapper(localName = "getCapinhaResponse", targetNamespace = "http://control/", className = "control.GetCapinhaResponse")
    @Action(input = "http://control/ControleInterface/getCapinhaRequest", output = "http://control/ControleInterface/getCapinhaResponse")
    public String getCapinha();

}
