
package control;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import model.Capinha;
import model.Celular;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InterfaceControle", targetNamespace = "http://control/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InterfaceControle {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "postCelular", targetNamespace = "http://control/", className = "control.PostCelular")
    @ResponseWrapper(localName = "postCelularResponse", targetNamespace = "http://control/", className = "control.PostCelularResponse")
    @Action(input = "http://control/InterfaceControle/postCelularRequest", output = "http://control/InterfaceControle/postCelularResponse")
    public void postCelular(
        @WebParam(name = "arg0", targetNamespace = "")
        Celular arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns control.Capinha
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCapinhaId", targetNamespace = "http://control/", className = "control.GetCapinhaId")
    @ResponseWrapper(localName = "getCapinhaIdResponse", targetNamespace = "http://control/", className = "control.GetCapinhaIdResponse")
    @Action(input = "http://control/InterfaceControle/getCapinhaIdRequest", output = "http://control/InterfaceControle/getCapinhaIdResponse")
    public Capinha getCapinhaId(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delCapinha", targetNamespace = "http://control/", className = "control.DelCapinha")
    @ResponseWrapper(localName = "delCapinhaResponse", targetNamespace = "http://control/", className = "control.DelCapinhaResponse")
    @Action(input = "http://control/InterfaceControle/delCapinhaRequest", output = "http://control/InterfaceControle/delCapinhaResponse")
    public String delCapinha(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "postCapinha", targetNamespace = "http://control/", className = "control.PostCapinha")
    @ResponseWrapper(localName = "postCapinhaResponse", targetNamespace = "http://control/", className = "control.PostCapinhaResponse")
    @Action(input = "http://control/InterfaceControle/postCapinhaRequest", output = "http://control/InterfaceControle/postCapinhaResponse")
    public void postCapinha(
        @WebParam(name = "arg0", targetNamespace = "")
        Capinha arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "putCapinha", targetNamespace = "http://control/", className = "control.PutCapinha")
    @ResponseWrapper(localName = "putCapinhaResponse", targetNamespace = "http://control/", className = "control.PutCapinhaResponse")
    @Action(input = "http://control/InterfaceControle/putCapinhaRequest", output = "http://control/InterfaceControle/putCapinhaResponse")
    public String putCapinha(
        @WebParam(name = "arg0", targetNamespace = "")
        Capinha arg0);

    /**
     * 
     * @return
     *     returns java.util.List<control.Capinha>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCapinha", targetNamespace = "http://control/", className = "control.GetCapinha")
    @ResponseWrapper(localName = "getCapinhaResponse", targetNamespace = "http://control/", className = "control.GetCapinhaResponse")
    @Action(input = "http://control/InterfaceControle/getCapinhaRequest", output = "http://control/InterfaceControle/getCapinhaResponse")
    public List<Capinha> getCapinha();

    /**
     * 
     * @param arg0
     * @return
     *     returns control.Celular
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCelularId", targetNamespace = "http://control/", className = "control.GetCelularId")
    @ResponseWrapper(localName = "getCelularIdResponse", targetNamespace = "http://control/", className = "control.GetCelularIdResponse")
    @Action(input = "http://control/InterfaceControle/getCelularIdRequest", output = "http://control/InterfaceControle/getCelularIdResponse")
    public Celular getCelularId(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "putCelular", targetNamespace = "http://control/", className = "control.PutCelular")
    @ResponseWrapper(localName = "putCelularResponse", targetNamespace = "http://control/", className = "control.PutCelularResponse")
    @Action(input = "http://control/InterfaceControle/putCelularRequest", output = "http://control/InterfaceControle/putCelularResponse")
    public String putCelular(
        @WebParam(name = "arg0", targetNamespace = "")
        Celular arg0);

    /**
     * 
     * @return
     *     returns java.util.List<control.Celular>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCelular", targetNamespace = "http://control/", className = "control.GetCelular")
    @ResponseWrapper(localName = "getCelularResponse", targetNamespace = "http://control/", className = "control.GetCelularResponse")
    @Action(input = "http://control/InterfaceControle/getCelularRequest", output = "http://control/InterfaceControle/getCelularResponse")
    public List<Celular> getCelular();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delCelular", targetNamespace = "http://control/", className = "control.DelCelular")
    @ResponseWrapper(localName = "delCelularResponse", targetNamespace = "http://control/", className = "control.DelCelularResponse")
    @Action(input = "http://control/InterfaceControle/delCelularRequest", output = "http://control/InterfaceControle/delCelularResponse")
    public String delCelular(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

}
